name: Compile

on: [push]

jobs:
  compile:
    strategy:
      matrix:
        device-os-version: [ '4.x', '5.x' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-platform-name: 'tracker'
          device-os-version: '${{ matrix.device-os-version }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: monitoredge-artifacts-${{ matrix.device-os-version }}
          path: |
            ${{ steps.compile.outputs.firmware-path }}
            ${{ steps.compile.outputs.target-path }}
