name: Compile

on: [push]

jobs:
  compile:
    strategy:
      matrix:
        device-os-version: [ '4.0.2', '5.3.1' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@main
        with:
          particle-platform-name: 'tracker'
          device-os-version: '${{ matrix.device-os-version }}'
          sources-folder: '.'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: monitoredge-firmware-deviceos-${{ matrix.device-os-version }}
          path: ${{ steps.compile.outputs.artifact-path }}
